import Donation from "../db.json";
import styled from "styled-components";
import Head from "next/head";
import { useState } from "react";

export default function HomePage({ donations }) {
  return (
    <>
      <StyledList>
        {donations.map((donation) => (
          <StyledCard key={donation.id}>
            <p>{donation.image}</p>
            <p>{donation.category}</p>
            <p>{donation.description}</p>
            <p>{donation.distance}</p>
            <p>{donation.good_before}</p>
            <p>{donation.contact_information}</p>
            {/* <label htmlFor="html">bio</label> */}
            <input type="checkbox" name="" id="" checked={donation.tag1} />
            {/*
            <input
              type="checkbox"
              name=""
              id=""
              checked={css}
              onChange={(e) => setCss(e.target.checked)}
            />
            <label htmlFor="html">Flexbox</label>
            <input
              type="checkbox"
              name=""
              id=""
              checked={flexbox}
              onChange={(e) => setFlexbox(e.target.checked)}
            />
            */}
          </StyledCard>
        ))}
      </StyledList>
      <Head>
        <title>Die Essensretter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
}
const StyledCard = styled.li`
  // z-index: 1;
  border: 2px solid black;

  text-align: center;
  width: 100%;
  padding: 0;
  margin: 0;
`;
const StyledList = styled.ul`
  list-style: none;
`;
