import styled from "styled-components";
import Head from "next/head";

export default function HomePage({ donations }) {
  return (
    <>
      <StyledList>
        {donations.map((donation) => (
          <StyledCard key={donation.id}>
            <p>{donation.image}</p>
            <p>Kategorie: {donation.category}</p>
            <p>Beschreibung: {donation.description}</p>
            <p>Entfernung: {donation.distance}</p>
            <p>Haltbar bis: {donation.good_before}</p>
            <p>Kontakt: {donation.contact_information}</p>
          </StyledCard>
        ))}
      </StyledList>
      <Head>
        <title>Die Essensretter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
}
const StyledCard = styled.li`
  // z-index: 1;
  border: 2px solid black;

  text-align: center;
  width: 100%;
  padding: 0;
  margin: 0;
`;
const StyledList = styled.ul`
  list-style: none;
`;
